@extends('layouts.app')
@section('content')
<main class="mx-auto max-w-7xl px-6 py-10">
    <h1 class="text-3xl font-bold">Product variants</h1><p class="mt-1 text-slate-600">Sellable catalog items and their current stock.</p>
    <form method="GET" action="{{ route('product-variants.index') }}" class="mt-6 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4">
        <label><span class="text-sm font-medium">Search</span><input name="search" value="{{ $search }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"></label>
        <label><span class="text-sm font-medium">Category</span><select name="category" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">All</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($categoryId===$category->id)>{{ $category->name }}</option>@endforeach</select></label>
        <label><span class="text-sm font-medium">Product</span><select name="product" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">All</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($productId===$product->id)>{{ $product->name }}</option>@endforeach</select></label>
        <label><span class="text-sm font-medium">Unit</span><select name="unit" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">All</option>@foreach(\App\Models\ProductVariant::SUPPORTED_UNITS as $unitOption)<option value="{{ $unitOption }}" @selected($unit===$unitOption)>{{ $unitOption }}</option>@endforeach</select></label>
        @if($admin)<label><span class="text-sm font-medium">Status</span><select name="status" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2">@foreach(['active'=>'Active','archived'=>'Archived','all'=>'All'] as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select></label>@endif
        <label class="flex items-end gap-2 pb-2"><input type="checkbox" name="low_stock" value="1" @checked($lowStock)><span class="text-sm font-medium">Low stock only</span></label>
        <div class="flex items-end"><button class="w-full rounded-lg bg-amber-600 px-4 py-2 font-semibold text-white">Apply filters</button></div>
    </form>
    <div class="mt-6 overflow-hidden rounded-xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr><th class="px-3 py-3 text-left text-sm">Product</th><th class="px-3 py-3 text-left text-sm">Identity</th><th class="px-3 py-3 text-left text-sm">Mode</th>@if($admin)<th class="px-3 py-3 text-right text-sm">Cost price</th>@endif<th class="px-3 py-3 text-right text-sm">Selling price</th><th class="px-3 py-3 text-right text-sm">Stock / threshold</th>@if($admin)<th class="px-3 py-3 text-left text-sm">Status</th><th class="px-3 py-3 text-right text-sm">Actions</th>@endif</tr></thead><tbody class="divide-y">
        @forelse($variants as $variant)<tr><td class="px-3 py-3"><span class="font-medium">{{ $variant->product->name }}</span><br><span class="text-xs text-slate-500">{{ $variant->product->category->name }}</span></td><td class="px-3 py-3 text-sm">{{ collect([$variant->size,$variant->type_series,$variant->thickness])->filter(fn($value)=>$value!=='')->join(' · ') ?: 'Standard' }} · {{ $variant->unit }}</td><td class="px-3 py-3 text-sm capitalize">{{ $variant->quantity_mode }}</td>@if($admin)<td class="px-3 py-3 text-right">{{ $variant->cost_price === null ? '—' : number_format((float)$variant->cost_price,2) }}</td>@endif<td class="px-3 py-3 text-right">{{ number_format((float)$variant->selling_price,2) }}</td><td class="px-3 py-3 text-right"><span @class(['rounded px-2 py-1 text-sm','bg-red-100 text-red-800'=>(float)$variant->current_stock <= (float)$variant->low_stock_threshold])>{{ $variant->current_stock }} / {{ $variant->low_stock_threshold }}</span></td>@if($admin)<td class="px-3 py-3 capitalize">{{ $variant->status }}</td><td class="px-3 py-3"><div class="flex justify-end gap-2">@if($variant->status==='active')<a href="{{ route('product-variants.edit',$variant) }}" class="rounded border px-3 py-1.5 text-sm">Edit</a><form method="POST" action="{{ route('product-variants.archive',$variant) }}">@csrf @method('PATCH')<button class="rounded border border-red-300 px-3 py-1.5 text-sm text-red-700">Archive</button></form>@else<form method="POST" action="{{ route('product-variants.reactivate',$variant) }}">@csrf @method('PATCH')<button class="rounded border border-emerald-300 px-3 py-1.5 text-sm text-emerald-700">Reactivate</button></form>@endif</div></td>@endif</tr>@empty<tr><td colspan="9" class="px-4 py-10 text-center text-slate-500">No variants found.</td></tr>@endforelse
        </tbody></table></div></div><div class="mt-6">{{ $variants->links() }}</div>
</main>
@endsection
